name: PHPCS check

on: pull_request

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr
      - name: Install dependencies
        run:
          composer init --name=matomo/loginldap --quiet;
          composer --no-plugins config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true -n;
          composer config repositories.matomo-coding-standards vcs https://github.com/matomo-org/matomo-coding-standards -n;
          composer require matomo-org/matomo-coding-standards:dev-master;
          composer install --dev --prefer-dist --no-progress --no-suggest
      - name: Check PHP code styles
        id: phpcs
        run: ./vendor/bin/phpcs --report-full --standard=phpcs.xml --report-checkstyle=./phpcs-report.xml
      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml --prepend-filename
